personalized_activity_planning_task:
  description: >
    研究并找到目的地的有趣活动。
    重点关注适合露营者兴趣和年龄组以及同行人员的活动和事件。
    使用互联网搜索工具和推荐引擎收集信息。
    从用户输入{user_input}中提取以下信息：
    - 出发地和目的地
    - 旅行者年龄和同行人员
    - 酒店位置偏好
    - 交通方式
    - 旅行时长
    - 出发时间
    - 特殊需求（如儿童、老人、宠物等）
    注意：所有输出必须使用简体中文。
    如果已经获取了用户输入，直接使用该信息进行规划，不要再次请求用户输入。
  expected_output: >
    每天推荐的活动和事件列表。
    每个条目应包括活动名称、位置、简短描述，以及为什么适合该旅行者。
    以及潜在的评价和评分。
    所有内容必须使用简体中文输出。

restaurant_scenic_location_scout_task:
  description: >
    寻找目的地的高评分餐厅和美食体验。
    推荐风景优美的地点、以及适合露营的地点和有趣的活动。
    使用互联网搜索工具、餐厅评论网站和旅游指南。
    确保找到适合不同口味和预算的各种选择，以及它们的评分。
    从用户输入{user_input}中提取信息，了解用户的餐饮偏好和特殊需求。
    注意：所有输出必须使用简体中文。
    如果已经获取了用户输入，直接使用该信息进行规划，不要再次请求用户输入。
  expected_output: >
    每天推荐的餐厅、风景点、适合露营的地点和有趣活动的列表。
    每个条目应包括名称、位置（地址）、类型（菜系或活动类型）以及简短描述和评分。
    所有内容必须使用简体中文输出。

itinerary_compilation_task:
  description: >
    将所有研究的信息整合成目的地的详细每日行程。
    确保行程包含交通、酒店信息和所有计划的活动和餐饮体验。
    使用文本格式和文档创建工具来组织信息。
    从用户输入{user_input}中提取信息，确保最终行程符合用户的期望和特殊需求。
    注意：所有输出必须使用简体中文。
    如果获取了用户输入，直接使用该信息进行规划，不要再次请求用户输入。
  expected_output: >
    一份详细的行程文档，包含每日计划，包括交通、酒店详情、活动、餐厅和风景点。
    如果同行人员中有儿童，需要列出适合儿童的活动、餐厅、酒店等；
    如果同行人员有老人，需要列出适合老人的活动、餐厅、酒店、景点等；
    如果有宠物，需要列出可携带宠物的酒店、餐厅、景点等。
    所有内容必须使用简体中文输出。
